/**
 * Content Collections Configuration
 * Defines schema for static pages (MDX content) and team data
 */

import { defineCollection, z } from "astro:content";

const staticPages = defineCollection({
	type: "content",
	schema: z.object({
		title: z.string(),
		// Note: slug is auto-generated by Astro from the filename and should not be in schema
	}),
});

const team = defineCollection({
	type: "data",
	schema: ({ image }) =>
		z.array(
			z.object({
				name: z.string(),
				role: z.string(),
				image: image(),
			}),
		),
});

export const collections = {
	"static-pages": staticPages,
	team: team,
};
