/**
 * Content Collections Configuration
 * Defines schema for static pages (MDX content)
 */

import { defineCollection, z } from 'astro:content';

const staticPages = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    // Note: slug is auto-generated by Astro from the filename and should not be in schema
  }),
});

export const collections = {
  'static-pages': staticPages,
};
