/**
 * Content Collections Configuration
 * Defines schema for markdown pages (MDX content), team data, and speakers.
 */

import { defineCollection, z } from "astro:content";
import { file, glob } from "astro/loaders";
import { BASE_URL } from "@lib/sessionize";

const markdownPages = defineCollection({
	loader: glob({ base: "./src/markdown-pages", pattern: "**/*.mdx" }),
	schema: z.object({
		title: z.string(),
		lang: z.string().optional(),
		// Note: slug is auto-generated by Astro from the filename and should not be in schema
	}),
});

const team = defineCollection({
	loader: file("src/pages/team/members.json", {
		parser: (text) => [{ id: "members", members: JSON.parse(text) }],
	}),
	schema: ({ image }) =>
		z.object({
			id: z.string(),
			members: z.array(
				z.object({
					name: z.string(),
					role: z.string(),
					image: image(),
				}),
			),
		}),
});

const sponsors = defineCollection({
	loader: file("src/pages/home-page/sections/SponsorsList/sponsors.json", {
		parser: (text) => [{ id: "list", tiers: JSON.parse(text) }],
	}),
	schema: ({ image }) =>
		z.object({
			id: z.string(),
			tiers: z.array(
				z.object({
					title: z.string(),
					tier: z.string(),
					sponsors: z.array(
						z.object({
							name: z.string(),
							url: z.string().url(),
							logo: image(),
						}),
					),
				}),
			),
		}),
});

const speakers = defineCollection({
	loader: async () => {
		const response = await fetch(`${BASE_URL}/Speakers`);
		if (!response.ok) {
			throw new Error(`Failed to load speakers: ${response.status}`);
		}
		const data = (await response.json()) as Array<Record<string, unknown>>;
		return data.map((speaker) => ({
			id: String(speaker.id ?? ""),
			...speaker,
			links: Array.isArray(speaker.links) ? speaker.links : [],
			sessions: Array.isArray(speaker.sessions) ? speaker.sessions : [],
		}));
	},
	schema: z.object({
		id: z.string(),
		firstName: z.string(),
		lastName: z.string(),
		fullName: z.string(),
		bio: z.string().optional(),
		tagLine: z.string().nullable().optional(),
		profilePicture: z.string().url(),
		sessions: z.array(
			z.object({
				id: z.number(),
				name: z.string(),
			}),
		),
		isTopSpeaker: z.boolean().optional(),
		links: z.array(
			z.object({
				title: z.string(),
				url: z.string().url(),
				linkType: z.string(),
			}),
		),
		categories: z
			.array(
				z.object({
					id: z.number(),
					name: z.string(),
				}),
			)
			.optional(),
	}),
});

const sessions = defineCollection({
	loader: async () => {
		const response = await fetch(`${BASE_URL}/Sessions`);
		if (!response.ok) {
			throw new Error(`Failed to load sessions: ${response.status}`);
		}

		const data = (await response.json()) as Array<Record<string, unknown>>;

		return data.flatMap((group) => {
			const groupedSessions = Array.isArray(group.sessions) ? group.sessions : [];

			return groupedSessions.map((session) => {
				const sessionData = session as Record<string, unknown>;

				return {
					id: String(sessionData.id ?? ""),
					title: String(sessionData.title ?? ""),
					description: typeof sessionData.description === "string" ? sessionData.description : "",
					startsAt: typeof sessionData.startsAt === "string" ? sessionData.startsAt : null,
					endsAt: typeof sessionData.endsAt === "string" ? sessionData.endsAt : null,
					room: typeof sessionData.room === "string" ? sessionData.room : null,
					speakers: Array.isArray(sessionData.speakers)
						? (sessionData.speakers as Array<Record<string, unknown>>).map((speaker) => ({
								id: String(speaker.id ?? ""),
								name: String(speaker.name ?? ""),
							}))
						: [],
				};
			});
		});
	},
	schema: z.object({
		id: z.string(),
		title: z.string(),
		description: z.string(),
		startsAt: z.string().nullable(),
		endsAt: z.string().nullable(),
		room: z.string().nullable(),
		speakers: z.array(
			z.object({
				id: z.string(),
				name: z.string(),
			}),
		),
	}),
});

export const collections = {
	"markdown-pages": markdownPages,
	team,
	sponsors,
	speakers,
	sessions,
};
