/**
 * Content Collections Configuration
 * Defines schema for static pages (MDX content), team data, and speakers.
 */

import { defineCollection, z } from "astro:content";
import { file, glob } from "astro/loaders";

const staticPages = defineCollection({
	loader: glob({ base: "./src/content/static-pages", pattern: "**/*.mdx" }),
	schema: z.object({
		title: z.string(),
		// Note: slug is auto-generated by Astro from the filename and should not be in schema
	}),
});

const team = defineCollection({
	loader: file("src/content/team/members.json", {
		parser: (text) => [{ id: "members", members: JSON.parse(text) }],
	}),
	schema: ({ image }) =>
		z.object({
			id: z.string(),
			members: z.array(
				z.object({
					name: z.string(),
					role: z.string(),
					image: image(),
				}),
			),
		}),
});

const speakers = defineCollection({
	loader: async () => {
		const response = await fetch("https://sessionize.com/api/v2/fetamiym/view/Speakers");
		if (!response.ok) {
			throw new Error(`Failed to load speakers: ${response.status}`);
		}
		const data = (await response.json()) as Array<Record<string, unknown>>;
		return data.map((speaker) => ({
			id: String(speaker.id ?? ""),
			...speaker,
			links: Array.isArray(speaker.links) ? speaker.links : [],
			sessions: Array.isArray(speaker.sessions) ? speaker.sessions : [],
		}));
	},
	schema: z.object({
		id: z.string(),
		firstName: z.string(),
		lastName: z.string(),
		fullName: z.string(),
		bio: z.string().optional(),
		tagLine: z.string().nullable().optional(),
		profilePicture: z.string().url(),
		sessions: z.array(
			z.object({
				id: z.number(),
				name: z.string(),
			}),
		),
		isTopSpeaker: z.boolean().optional(),
		links: z.array(
			z.object({
				title: z.string(),
				url: z.string().url(),
				linkType: z.string(),
			}),
		),
		categories: z
			.array(
				z.object({
					id: z.number(),
					name: z.string(),
				}),
			)
			.optional(),
	}),
});

export const collections = {
	"static-pages": staticPages,
	team,
	speakers,
};
